// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sukwzdwszhftxlqbhzys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1a3d6ZHdzemhmdHhscWJoenlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNjMxNTMsImV4cCI6MjA1ODYzOTE1M30.uSV5mbYNBr0S1_DfgQ-Nqif9gYSA1y_zZCt6mvVcpns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);